### ISSUE TITLE
ANR when user selects `No` when asked for permissions

### ISSUE THREAD

**Issue by diogowbrito** [microsoftgraph/msgraph-sdk-android#20] opened 2016-07-01 10:07 UTC
If the user taps `No` while in the permissions screen (after user has already logged in) the application will get stuck. I'm using the `MSAAuthAndroidAdapter` and seems like no callback in called.

When `Yes` is tapped `onAuthComplete(final LiveStatus status,…)` is called. However, when tapping `No` then `onAuthError(final LiveAuthException exception,…)` is never called, leaving the app in an ANR state.

This is the related screen:
![permission_screen](https://cloud.githubusercontent.com/assets/739100/16518651/e8742850-3f7b-11e6-97b1-bcaecd9be570.png)

**Comment by iambmelt** [comment] 2016-07-01 17:03
@diogowbrito Thanks for reporting this issue; I'm able to reproduce this issue - I'm currently investigating and will update this thread with my findings as soon as possible.

/cc @peternied @shiftylogic

**Comment by iambmelt** [comment] 2016-07-01 17:23
After an initial investigation; the error appears to be caused by [this check](https://github.com/OfficeDev/msa-auth-for-android/blob/master/src/main/java/com/microsoft/services/msa/AuthorizationRequest.java#L140-L142) in [OfficeDev/msa-auth-for-android](https://github.com/OfficeDev/msa-auth-for-android)

![screen shot 2016-07-01 at 10 20 08 am](https://cloud.githubusercontent.com/assets/990063/16529070/95b8079a-3f75-11e6-9afd-7233479668fb.png)

I'll open an issue in this dependency project, and provide the link here once posted.

---

**edit

Associated project issue is now tracked [here](https://github.com/OfficeDev/msa-auth-for-android/issues/32)

/cc @diogowbrito

**Comment by diogowbrito** [comment] 2016-07-01 17:33
Awesome, thanks @iambmelt  👍

**Comment by iambmelt** [comment] 2016-07-14 00:49
Closing this issue. Please refer to [msa-auth-for-android/issues/32](https://github.com/OfficeDev/msa-auth-for-android/issues/32) for tracking

**Closed as completed by iambmelt** 2016-07-14 00:49 UTC
Labels: bug
